name: Build and deploy container

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - 'README.md'
      - 'LICENSE'

env:
  REGISTRY: ghcr.io

jobs:
  configure-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - id: find-targets
        run: |
          targets=$(cat docker-bake.hcl | grep target | grep -e latest -e supported | grep -v -e version | sed 's/target "\(.*\)".*/"\1"/' | tr '\n' ',' | sed 's/,*$//')
          echo "targets found:"
          echo ${targets}
          echo "targets=[${targets}]" >> ${GITHUB_OUTPUT}
    outputs:
      targets: ${{ steps.find-targets.outputs.targets }}

  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - configure-build
    
    strategy:
      matrix:
        target: ${{ fromJson(needs.configure-build.outputs.targets) }}

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          push: true
          targets: ${{ matrix.target }}
    